name: sih_internship_app
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  animated_bottom_navigation_bar: ^1.3.3
  fluttertoast: ^8.2.8
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  google_sign_in: ^6.2.2
  get: ^4.6.6
  image_picker: ^1.1.2
  flutter_launcher_icons: ^0.14.1
  http: ^1.2.2
  path: ^1.9.0
  intl: ^0.20.1
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#FFFFFF"  # You can use a color or a background image
  adaptive_icon_foreground: "assets/images/logo.png" # Only for Android

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
