// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcBq5zRIpaYPTw3GsX9DVArHon4RvZQTM',
    appId: '1:997916127203:web:d2881579ea3bb41bbbfad6',
    messagingSenderId: '997916127203',
    projectId: 'rajasthan-connect-3f1d3',
    authDomain: 'rajasthan-connect-3f1d3.firebaseapp.com',
    storageBucket: 'rajasthan-connect-3f1d3.firebasestorage.app',
    measurementId: 'G-HN4B1K9MP4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgGg0vVcqSUkiSSIbaTbdti2IqEGY7alE',
    appId: '1:997916127203:android:ac767872049582c2bbfad6',
    messagingSenderId: '997916127203',
    projectId: 'rajasthan-connect-3f1d3',
    storageBucket: 'rajasthan-connect-3f1d3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyIUuLE4A5hDih4v3pRCwDg_RXwilyWNE',
    appId: '1:997916127203:ios:fcdfd1f07f229dfbbbfad6',
    messagingSenderId: '997916127203',
    projectId: 'rajasthan-connect-3f1d3',
    storageBucket: 'rajasthan-connect-3f1d3.firebasestorage.app',
    iosClientId: '997916127203-id9ndicttqti1vrco1a31273hi3rpu3o.apps.googleusercontent.com',
    iosBundleId: 'com.example.sihInternshipApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyIUuLE4A5hDih4v3pRCwDg_RXwilyWNE',
    appId: '1:997916127203:ios:fcdfd1f07f229dfbbbfad6',
    messagingSenderId: '997916127203',
    projectId: 'rajasthan-connect-3f1d3',
    storageBucket: 'rajasthan-connect-3f1d3.firebasestorage.app',
    iosClientId: '997916127203-id9ndicttqti1vrco1a31273hi3rpu3o.apps.googleusercontent.com',
    iosBundleId: 'com.example.sihInternshipApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcBq5zRIpaYPTw3GsX9DVArHon4RvZQTM',
    appId: '1:997916127203:web:1247006acd459da0bbfad6',
    messagingSenderId: '997916127203',
    projectId: 'rajasthan-connect-3f1d3',
    authDomain: 'rajasthan-connect-3f1d3.firebaseapp.com',
    storageBucket: 'rajasthan-connect-3f1d3.firebasestorage.app',
    measurementId: 'G-Z0MMF4E3JZ',
  );
}
